#!/bin/bash

touch /root/.system
clear
echo -e "\033[1;36m┌─────────────────────────────────────────┐\033[0m" | lolcat
echo -e "        =[ member v2ray account ]=         "
echo -e "\033[1;36m└─────────────────────────────────────────┐\033[0m" | lolcat
echo -n > /root/.accsess.log
data=( $(cat /etc/v2ray/config.json | grep '###' | cut -d ' ' -f 2 | sort | uniq) )
for user in "${data[@]}"
do
echo > /dev/null
jum=$(cat /etc/v2ray/config.json | grep -c '###' | awk '{print $1/2}')
if [[ $jum -gt 0 ]]; then
exp=$(grep -wE "^### $user" "/etc/v2ray/config.json" | cut -d ' ' -f 3 | sort | uniq)
echo -e "  \e[33;1mUser\e[32;1m  : $user"
echo -e "  \e[33;1mExp\e[32;1m   : $exp"
echo -e "\033[1;36m┌─────────────────────────────────────────┘\033[0m" | lolcat
echo "slot" >> /root/.system
else
echo > /dev/null
fi
sleep 0.1
done
aktif=$(cat /root/.system | wc -l)
echo -e "\033[1;36m┌─────────────────────────────────────────┐\033[0m" | lolcat
echo -e "   $aktif Member Active"
echo -e "\033[1;36m└─────────────────────────────────────────┘\033[0m" | lolcat
sed -i "d" /root/.system