#!/bin/bash

# Warna
green='\e[32m'
yellow='\e[33m'
red='\e[31m'
reset='\e[0m'

# Cek status service
check_status() {
    local service_name=$1
    systemctl is-active --quiet "$service_name"
    if [ $? -eq 0 ]; then
        echo "on"
    else
        echo "off"
    fi
}

# Ambil status dropbear & websocket
status_dropbear=$(check_status dropbear)
status_websocket=$(check_status ws)

# Tentukan warna status
if [[ "$status_dropbear" == "on" && "$status_websocket" == "on" ]]; then
    status_all="${green}ON${reset}"
elif [[ "$status_dropbear" == "off" && "$status_websocket" == "off" ]]; then
    status_all="${red}OFF${reset}"
else
    status_all="${yellow}OFF${reset}"
fi

clear
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \E[0;100;33m          • SSH MANAGER •        \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " SSH Status : $status_all"
echo -e ""
echo -e " [\e[36m•1\e[0m] Create SSH Acount "
echo -e " [\e[36m•2\e[0m] Trial SSH Acount "
echo -e " [\e[36m•3\e[0m] List Member SSH Acount"
echo -e " [\e[36m•4\e[0m] Delete SSH Acount "
echo -e " [\e[36m•5\e[0m] Renew SSH Acount "
echo -e " [\e[36m•6\e[0m] Cek Users Login SSH "
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU\033[0m"
echo -e ""
echo -e "   Press x or [ Ctrl+C ] • To-Exit"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p " Select menu :  "  opt
echo -e ""
case $opt in
1) clear ; add-ssh ; exit ;;
2) clear ; trial-ssh ; exit ;;
3) clear ; list-ssh ; exit ;;
4) clear ; delete-ssh ; exit ;;
5) clear ; renew-ssh ; exit ;;
6) clear ; cek-ssh ; exit ;;
0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Anda salah tekan " ; sleep 1 ; menu-ssh ;;
esac